---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-deploy
  namespace: bggns
  labels:
    app: bggdb
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      namespace: bggns
      labels:
        app: bgg
        name: bggdb-po
    spec:
      containers:
      - name: dev-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret


