---
apiVersion: v1
kind: namespace
metadata:
  name: bggns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bggdb
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      abc: xyz
      app: bgg
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      namespace: bggns
      labels:
        app: bgg
        name: bggdb-po
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
      ports:
          - name: db-port
            containerPort: 3306
