---
apiVersion: v1
kind: Namespace
metadata:
  name: minns

---
apiVersion: v1 
kind: ConfigMap  
metadata:
  name: min-cm
  namespace: minns
data:
  MINIO_ROOT_USER: mohan
  MINIO_ROOT_PASSWORD: mohankannan

---
apiVersion: apps/v1
kind: Deployment  
metadata: 
  name: min-deploy
  namespace: minns 
  labels:
    app: minio
    name: min-deploy
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: minio 
      name: min-po 
  template: 
    metadata:
      name: min-po 
      labels:
        app: minio 
        name: min-po 
    spec:
      initContainers:
      - name: minio-init
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - bin/sh
        - -c 
        - "chown 1001:1001 /data"
        volumeMounts:
        - name: data-vol
          mountPath: /data/
      # securityContext:
      #   runAsUser: 1001
      #   runAsGroup: 1001
      #   fsGroup: 1001
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: min-pvc
      containers: 
      - name: min-container
        image: bitnami/minio:2024.3.10-debian-12-r0 
        imagePullPolicy: IfNotPresent
        command: ["minio"]
        args: ["server","--address=:9000", "--console-address=:9090","/data/minio/"] 
        envFrom:
        - configMapRef:
            name: min-cm
        ports:
        - name: server-port 
          containerPort: 9000
        - name: web-port 
          containerPort: 9090
        - name: metrics-port 
          containerPort: 900
        # livenessProbe:
        #   httpGet:
        #     path: /minio/health/live 
        #     port: metrics-port 
        #   periodSeconds: 30
        #   initialDelaySeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /minio/health/ready 
        #     port: metrics-port 
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 200m
            memory: 250Mi
        volumeMounts:
          - name: data-vol
            mountPath: /data/

---
apiVersion: v1
kind: PersistentVolumeClaim # pvc is namespace-scoped. persistentvolume is not namespace-scoped
metadata:
  name: min-pvc
  namespace: minns
  labels:
    app: minio
    name: min-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage # get storage classes by k get sc

--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: min-svc 
  namespace: minns 
  labels:
    app: minio
    name: min-svc 
spec:
  type: ClusterIP
  selector:
    app: minio 
    name: min-po
  ports:
  - name: svc-web-port 
    port: 9090
    targetPort: web-port
  - name: svc-server-port 
    port: 9000
    targetPort: server-port 
  # - name: svc-metrics-port 
  #   port: 900
  #   targetPort: metrics-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: min-ingress-data
  namespace: minns
  labels:
    app: minio
    type: min-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: data-167.172.6.249.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: min-svc
                port:
                  name: server-port 


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: min-ingress-console
  namespace: minns
  labels:
    app: minio
    type: min-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: console-167.172.6.249.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: min-svc
                port:
                  name: web-port
                  

# --- 
# apiVersion: v1 
# kind: Service 
# metadata: 
#   name: min-hsvc 
#   namespace: minns 
#   labels:
#     app: minio
#     name: min-hsvc 
# spec:
#   clusterIP: None
#   selector:
#     app: minio 
#     name: min-po
#   ports:
#   - name: svc-web-port 
#     port: 9090
#     targetPort: web-port
#   - name: svc-metrics-port 
#     port: 9000
#     targetPort: metrics-port


---
apiVersion: apps/v1 
kind: StatefulSet 
metadata:
  name: min-sts 
  namespace: minns
spec:
  replicas: 3
  serviceName: min-hsvc
  selector: 
    matchLabels:
      app: minio 
      name: min-po 
  template: 
    metadata:
      name: min-po 
      labels:
        app: minio 
        name: min-po 
    spec:
      containers: 
      - name: min-container
        image: chukmunnlee/dov-bear:v5 
        imagePullPolicy: IfNotPresent
        env: # environment variables
        - name: INSTANCE_HASH 
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: web-port 
          containerPort: 3000
        - name: metrics-port 
          containerPort: 3100
        livenessProbe:
          httpGet:
            path: /healthz 
            port: web-port
          periodSeconds: 30
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: 32m
            memory: 64Mi
          limits:
            cpu: 32m
            memory: 64Mi
